# Generated by Django 5.1.6 on 2025-02-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Commands",
            new_name="Command",
        ),
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
    ]
