# Generated by Django 5.1.6 on 2025-02-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="directory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.directory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="directory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.directory",
            ),
            preserve_default=False,
        ),
    ]
